spring:
  application:
    name: gateway-server
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

server:
  port: ${SERVER_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

info:
  app:
    name: ${spring.application.name}
    description: API gateway service for roots-app
    version: @project.version@

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,shutdown,gateway
  endpoint:
    gateway:
      access: unrestricted
    shutdown:
      access: unrestricted

web:
  client:
    origin: ${WEB_CLIENT_ORIGIN:http://localhost:3000}
