{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-server-db.fullname" . }}
  labels:
    {{- include "auth-server-db.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ required "mysql.rootPassword is required (or set mysql.existingSecret)" .Values.mysql.rootPassword | b64enc }}
{{- end }}