apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-server-db.fullname" . }}
  labels:
    {{- include "auth-server-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # clusterIP: None would make this headless, which is the more common choice for
  # StatefulSets when clients need to address the specific pod. A normal ClusterIP
  # is fine here since you only ever have 1 replica.
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.mysql.tcpPort }}
  selector:
    {{- include "auth-server-db.labels" . | nindent 4 }}