spring:
  application:
    name: simple-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWK_URI:http://localhost:9000/oauth2/jwks}

server:
  port: ${SERVER_PORT:8081}
