apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-server-redis.fullname" . }}
  labels:
    {{- include "auth-server-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "auth-server-redis.selectorLabels" . | nindent 4 }}
