spring:
  application:
    name: account-management
  datasource:
    url: ${MYSQL_AUTH_SERVER_DB_URL:jdbc:mysql://localhost:3308/auth-server-db}
    username: ${MYSQL_AUTH_SERVER_ROOT_USERNAME}
    password: ${MYSQL_AUTH_SERVER_ROOT_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWK_URI:http://localhost:9000/oauth2/jwks}

server:
  port: ${SERVER_PORT:8082}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}
info:
  app:
    name: ${spring.application.name}
    description: account management server for managing user account information
    version: @project.version@

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
  endpoint:
    shutdown:
      access: unrestricted
